test_size: 0.2
random_state: 42

n_trials: 10

selected_features:
  - V14
  - V12
  - V10
  - V4
  - V16
  - amount_x_V12
  - V7
  - Time
  - V20
  - Amount
  - hour_of_day
  - V22
  - amount_log
  - V1
  - V9
  - V19
  - amount_x_V14
  - V27
  - V18
  - V15
  - V5
  - V17
  - V3
  - V11
  - amount_x_V10
  - V2
  - V23
  - V6
  - V8
  - V21
  - amount_x_V17
  - V24
  - V28
  - V25